apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: postgresqlservices.yannic.codes
spec:
  scope: Namespaced
  group: yannic.codes
  names:
    kind: PostgreSQLService
    plural: postgresqlservices
    singular: postgresqlservice
    shortNames:
      - psql
      - postgres
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                name: 
                  type: string